config/routes.rb
WdiExercisr::Application.routes.draw do
  resources :exercises


  root :to => 'users#index'
  resources :user_sessions
  resources :users

  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
  attr_accessible :activity, :completed, :units, :value, :user_id
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  attr_accessible :email, :password, :password_confirmation, :name

  validates_length_of :password, :minimum => 3, :message => "password must be at least 3 characters long", :if => :password
  validates_confirmation_of :password, :message => "should match confirmation", :if => :password

  has_many :exercises
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :require_login

protected

  def not_authenticated
    redirect_to login_path, :alert => "Please login first."
  end
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  # GET /exercises
  # GET /exercises.json
  def index
    @exercises = Exercise.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @exercises }
    end
  end

  # GET /exercises/1
  # GET /exercises/1.json
  def show
    @exercise = Exercise.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @exercise }
    end
  end

  # GET /exercises/new
  # GET /exercises/new.json
  def new
    @exercise = Exercise.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @exercise }
    end
  end

  # GET /exercises/1/edit
  def edit
    @exercise = Exercise.find(params[:id])
  end

  # POST /exercises
  # POST /exercises.json
  def create
    @exercise = Exercise.new(params[:exercise])

    respond_to do |format|
      if @exercise.save
        format.html { redirect_to @exercise, notice: 'Exercise was successfully created.' }
        format.json { render json: @exercise, status: :created, location: @exercise }
      else
        format.html { render action: "new" }
        format.json { render json: @exercise.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /exercises/1
  # PUT /exercises/1.json
  def update
    @exercise = Exercise.find(params[:id])

    respond_to do |format|
      if @exercise.update_attributes(params[:exercise])
        format.html { redirect_to @exercise, notice: 'Exercise was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @exercise.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exercises/1
  # DELETE /exercises/1.json
  def destroy
    @exercise = Exercise.find(params[:id])
    @exercise.destroy

    respond_to do |format|
      format.html { redirect_to exercises_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_filter :require_login, :except => [:destroy]

  def new
    @user = User.new
  end

  def create
    respond_to do |format|
      if @user = login(params[:email], params[:password])
        format.html { redirect_back_or_to(:users, :notice => 'Login successful.') }
        format.xml { render :xml => @user, :status => :created, :location => @user }
      else
        format.html { flash.now[:alert] = "Login failed."; render :action => "new" }
        format.xml { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    logout
    redirect_to(:users, :notice => 'Logged out!')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :require_login, :only => [:index, :new, :create]

  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to(:users, :notice => 'User was successfully created.') }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/exercises/_form.html.haml
= form_for @exercise do |f|
  - if @exercise.errors.any?
    #error_explanation
      %h2= "#{pluralize(@exercise.errors.count, "error")} prohibited this exercise from being saved:"
      %ul
        - @exercise.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :activity
    = f.text_field :activity
  .field
    = f.label :value
    = f.text_field :value
  .field
    = f.label :units
    = f.number_field :units
  .field
    = f.label :completed
    = f.text_field :completed
  .actions
    = f.submit 'Save'

app/views/exercises/edit.html.haml
%h1 Editing exercise

= render 'form'

= link_to 'Show', @exercise
\|
= link_to 'Back', exercises_path

app/views/exercises/index.html.haml
%h1 Listing exercises

%table
  %tr
    %th Activity
    %th Value
    %th Units
    %th Completed
    %th
    %th
    %th

  - @exercises.each do |exercise|
    %tr
      %td= exercise.activity
      %td= exercise.value
      %td= exercise.units
      %td= exercise.completed
      %td= link_to 'Show', exercise
      %td= link_to 'Edit', edit_exercise_path(exercise)
      %td= link_to 'Destroy', exercise, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Exercise', new_exercise_path

app/views/exercises/new.html.haml
%h1 New exercise

= render 'form'

= link_to 'Back', exercises_path

app/views/exercises/show.html.haml
%p#notice= notice

%p
  %b Activity:
  = @exercise.activity
%p
  %b Value:
  = @exercise.value
%p
  %b Units:
  = @exercise.units
%p
  %b Completed:
  = @exercise.completed

= link_to 'Edit', edit_exercise_path(@exercise)
\|
= link_to 'Back', exercises_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Exercisr</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if current_user %>
  <%= link_to "Edit Profile", edit_user_path(current_user.id) %>
  <%= link_to "Logout", :logout %>
<% else %>
  <%= link_to "Register", new_user_path %> |
  <%= link_to "Login", :login %>
<% end %>

<div>
  <p id="notice"><%= notice %></p>
  <p id="alert"><%= alert %></p>
</div>

<%= yield %>

</body>
</html>

app/views/user_sessions/_form.html.haml
= form_tag user_sessions_path, :method => :post do
  .field
    = label_tag :email
    = text_field_tag :email
  .field
    = label_tag :password
    = password_field_tag :password
  .actions
    = submit_tag "Login"

app/views/user_sessions/create.html.haml
%h1 UserSessions#create
%p Find me in app/views/user_sessions/create.html.haml

app/views/user_sessions/destroy.html.haml
%h1 UserSessions#destroy
%p Find me in app/views/user_sessions/destroy.html.haml

app/views/user_sessions/new.html.haml
%h1 Login

= render 'form'

app/views/users/_form.html.haml
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :password
    = f.password_field :password
  .field
    = f.label :password_confirmation
    = f.password_field :password_confirmation
  .actions
    = f.submit 'Save'

app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

app/views/users/index.html.haml
%h1 Listing users

%table
  %tr
    %th Email
    %th
    %th
    %th

  - @users.each do |user|
    %tr
      %td= user.email
      %td= link_to 'Show', user
      %td= link_to 'Edit', edit_user_path(user)
      %td= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New User', new_user_path

app/views/users/new.html.haml
%h1 New user

= render 'form'

= link_to 'Back', users_path

app/views/users/show.html.haml
%p#notice= notice

%p
  %b Email:
  = @user.email
%p
  %b Name:
  = @user.name

%p
  %b Exercises:
  %br
  %br
  - @user.exercises.each do |exercise|
    On
    = exercise.completed
    you
    = exercise.activity
    for
    = exercise.value
    = exercise.units

= link_to 'Edit', edit_user_path(@user)
\|
= link_to 'Back', users_path